CREATE DATABASE TASKDB;
USE TASKDB;

-- REGIONS TABLE
CREATE TABLE REGIONS (
    REGION_ID INT PRIMARY KEY,
    REGION_NAME VARCHAR(100)
);

-- COUNTRIES TABLE
CREATE TABLE COUNTRIES (
    COUNTRY_ID INT PRIMARY KEY,
    COUNTRY_NAME VARCHAR(100),
    REGION_ID INT,
    FOREIGN KEY (REGION_ID) REFERENCES REGIONS(REGION_ID)
);

-- LOCATIONS TABLE
CREATE TABLE LOCATIONS (
    LOCATION_ID INT PRIMARY KEY,
    ADDRESS VARCHAR(255),
    POSTAL_CODE VARCHAR(20),
    CITY VARCHAR(100),
    STATE VARCHAR(100),
    COUNTRY_ID INT,
    FOREIGN KEY (COUNTRY_ID) REFERENCES COUNTRIES(COUNTRY_ID)
);

-- WAREHOUSES TABLE
CREATE TABLE WAREHOUSES (
    WAREHOUSE_ID INT PRIMARY KEY,
    WAREHOUSE_NAME VARCHAR(255),
    LOCATION_ID INT,
    FOREIGN KEY (LOCATION_ID) REFERENCES LOCATIONS(LOCATION_ID)
);

-- PRODUCT_CATEGORIES TABLE
CREATE TABLE PRODUCT_CATEGORIES (
    CATEGORY_ID INT PRIMARY KEY,
    CATEGORY_NAME VARCHAR(100)
);

-- PRODUCTS TABLE
CREATE TABLE PRODUCTS (
    PRODUCT_ID INT PRIMARY KEY,
    PRODUCT_NAME VARCHAR(255),
    DESCRIPTION TEXT,
    STANDARD_COST DECIMAL(10,2),
    LIST_PRICE DECIMAL(10,2),
    CATEGORY_ID INT,
    FOREIGN KEY (CATEGORY_ID) REFERENCES PRODUCT_CATEGORIES(CATEGORY_ID)
);

-- INVENTORIES TABLE
CREATE TABLE INVENTORIES (
    PRODUCT_ID INT,
    WAREHOUSE_ID INT,
    QUANTITY INT,
    PRIMARY KEY (PRODUCT_ID, WAREHOUSE_ID),
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(PRODUCT_ID),
    FOREIGN KEY (WAREHOUSE_ID) REFERENCES WAREHOUSES(WAREHOUSE_ID)
);

-- CUSTOMERS TABLE
CREATE TABLE CUSTOMERS (
    CUSTOMER_ID INT PRIMARY KEY,
    NAME VARCHAR(255),
    ADDRESS VARCHAR(255),
    WEBSITE VARCHAR(255),
    CREDIT_LIMIT DECIMAL(15,2)
);

-- CONTACTS TABLE
CREATE TABLE CONTACTS (
    CONTACT_ID INT PRIMARY KEY,
    FIRST_NAME VARCHAR(100),
    LAST_NAME VARCHAR(100),
    EMAIL VARCHAR(255),
    PHONE VARCHAR(50),
    CUSTOMER_ID INT,
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID)
);

-- EMPLOYEES TABLE
CREATE TABLE EMPLOYEES (
    EMPLOYEE_ID INT PRIMARY KEY,
    FIRST_NAME VARCHAR(100),
    LAST_NAME VARCHAR(100),
    EMAIL VARCHAR(255),
    PHONE VARCHAR(50),
    HIRE_DATE DATE,
    MANAGER_ID INT,
    JOB_TITLE VARCHAR(100),
    FOREIGN KEY (MANAGER_ID) REFERENCES EMPLOYEES(EMPLOYEE_ID)
);

-- ORDERS TABLE
CREATE TABLE ORDERS (
    ORDER_ID INT PRIMARY KEY,
    CUSTOMER_ID INT,
    STATUS VARCHAR(50),
    SALESMAN_ID INT,
    ORDER_DATE DATE,
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID),
    FOREIGN KEY (SALESMAN_ID) REFERENCES EMPLOYEES(EMPLOYEE_ID)
);

-- ORDER_ITEMS TABLE
CREATE TABLE ORDER_ITEMS (
    ORDER_ID INT,
    ITEM_ID INT,
    PRODUCT_ID INT,
    QUANTITY INT,
    UNIT_PRICE DECIMAL(10,2),
    PRIMARY KEY (ORDER_ID, ITEM_ID),
    FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ORDER_ID),
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(PRODUCT_ID)
);

show tables;
